# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 405bc25b2ed508bceec7334c35617e1491a0ee9d140c5f75225036d26fbfa0ed6d79be3ab839027f4998a63abacdc5fa65940ad98146f71d1c19f81e89128c77

test:
  secret_key_base: 627a51cdf77b4b7b6261fb5448d1518cda9994f02090ef4cf5bef368bf72e8fa1fe1350d4e33ac6d65936a8fb2c411450a9ef8d631c575aeac1d6ae5e7084a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
